add_subdirectory(resolv)

add_entrypoint_object(
  freeaddrinfo
  SRCS
    freeaddrinfo.cpp
  HDRS
    freeaddrinfo.h
  DEPENDS
    libc.hdr.func.free
    libc.hdr.types.struct_addrinfo
    libc.src.__support.common
)

add_entrypoint_object(
  getaddrinfo
  SRCS
    getaddrinfo.cpp
  HDRS
    getaddrinfo.h
  DEPENDS
    .freeaddrinfo
    libc.hdr.errno_macros
    libc.hdr.func.free
    libc.hdr.func.malloc
    libc.hdr.netdb_macros
    libc.hdr.sys_socket_macros
    libc.include.llvm-libc-macros.netinet_in_macros
    libc.hdr.types.struct_addrinfo
    libc.hdr.types.struct_sockaddr_in
    libc.hdr.types.struct_sockaddr_in6
    libc.src.__support.common
    libc.src.__support.ctype_utils
    libc.src.__support.libc_errno
    libc.src.__support.str_to_integer
    libc.src.netdb.resolv.lookup
    libc.src.netdb.resolv.services
    libc.src.string.memory_utils.inline_memcpy
    libc.src.string.string_utils
)

add_entrypoint_object(
  gai_strerror
  SRCS
    gai_strerror.cpp
  HDRS
    gai_strerror.h
  DEPENDS
    libc.hdr.netdb_macros
)

add_entrypoint_object(
  getnameinfo
  SRCS
    getnameinfo.cpp
  HDRS
    getnameinfo.h
  DEPENDS
    libc.hdr.netdb_macros
    libc.hdr.types.socklen_t
    libc.hdr.types.struct_sockaddr
    libc.hdr.types.struct_sockaddr_in
    libc.hdr.types.struct_sockaddr_in6
    libc.include.sys_socket
    libc.src.arpa.inet.inet_ntop
    libc.src.arpa.inet.ntohs
    libc.src.string.string_utils
)

add_entrypoint_object(
  __h_errno_location
  SRCS
    __h_errno_location.cpp
  HDRS
    __h_errno_location.h
  DEPENDS
    libc.src.__support.macros.attributes
)

add_object_library(
  hostent_storage
  SRCS
    hostent_storage.cpp
  HDRS
    hostent_storage.h
  DEPENDS
    libc.hdr.netdb_macros
    libc.hdr.sys_socket_macros
    libc.hdr.types.struct_hostent
    libc.src.__support.macros.attributes
    libc.src.netdb.__h_errno_location
    libc.src.netdb.resolv.lookup
    libc.src.string.memory_utils.inline_memcpy
    libc.src.string.string_utils
)

add_entrypoint_object(
  gethostbyname
  SRCS
    gethostbyname.cpp
  HDRS
    gethostbyname.h
  DEPENDS
    .hostent_storage
    libc.hdr.sys_socket_macros
    libc.hdr.types.struct_hostent
    libc.src.__support.common
)

add_entrypoint_object(
  gethostbyname2
  SRCS
    gethostbyname2.cpp
  HDRS
    gethostbyname2.h
  DEPENDS
    .hostent_storage
    libc.hdr.sys_socket_macros
    libc.hdr.types.struct_hostent
    libc.src.__support.common
)

add_object_library(
  proto_storage
  SRCS
    proto_storage.cpp
  HDRS
    proto_storage.h
  DEPENDS
    libc.src.__support.macros.attributes
    libc.src.__support.macros.config
    libc.src.netdb.resolv.protocols
)

add_entrypoint_object(
  getprotobyname
  SRCS
    getprotobyname.cpp
  HDRS
    getprotobyname.h
  DEPENDS
    .proto_storage
    libc.hdr.types.struct_protoent
    libc.src.__support.common
    libc.src.__support.macros.config
    libc.src.netdb.resolv.protocols
)

add_entrypoint_object(
  getprotobynumber
  SRCS
    getprotobynumber.cpp
  HDRS
    getprotobynumber.h
  DEPENDS
    .proto_storage
    libc.hdr.types.struct_protoent
    libc.src.__support.common
    libc.src.__support.macros.config
    libc.src.netdb.resolv.protocols
)

add_entrypoint_object(
  getprotoent
  SRCS
    getprotoent.cpp
  HDRS
    getprotoent.h
  DEPENDS
    .proto_storage
    libc.hdr.types.struct_protoent
    libc.src.__support.common
    libc.src.__support.macros.config
    libc.src.netdb.resolv.protocols
)

add_entrypoint_object(
  setprotoent
  SRCS
    setprotoent.cpp
  HDRS
    setprotoent.h
  DEPENDS
    libc.hdr.types.struct_protoent
    libc.src.__support.common
    libc.src.__support.macros.config
    libc.src.netdb.resolv.protocols
)

add_entrypoint_object(
  endprotoent
  SRCS
    endprotoent.cpp
  HDRS
    endprotoent.h
  DEPENDS
    libc.hdr.types.struct_protoent
    libc.src.__support.common
    libc.src.__support.macros.config
    libc.src.netdb.resolv.protocols
)

add_entrypoint_object(
  getservbyname
  SRCS
    getservbyname.cpp
  HDRS
    getservbyname.h
  DEPENDS
    libc.hdr.types.struct_servent
    libc.src.__support.common
    libc.src.__support.macros.attributes
    libc.src.netdb.resolv.services
    libc.src.string.memory_utils.inline_memcpy
    libc.src.string.string_utils
)
