add_custom_target(libc_fcntl_unittests)

add_subdirectory(testdata)

add_libc_test(
  creat_test
  SUITE
    libc_fcntl_unittests
  SRCS
    creat_test.cpp
  DEPENDS
    libc.hdr.sys_stat_macros
    libc.include.fcntl
    libc.src.errno.errno
    libc.src.fcntl.creat
    libc.src.fcntl.open
    libc.src.unistd.close
    libc.test.UnitTest.ErrnoCheckingTest
    libc.test.UnitTest.ErrnoSetterMatcher
)

add_libc_test(
  fcntl_test
  SUITE
    libc_fcntl_unittests
  SRCS
    fcntl_test.cpp
  DEPENDS
    libc.include.fcntl
    libc.src.errno.errno
    libc.src.fcntl.fcntl
    libc.src.fcntl.open
    libc.src.unistd.close
    libc.src.unistd.getpid
    libc.hdr.types.struct_flock
    libc.hdr.fcntl_macros
    libc.hdr.stdio_macros
    libc.hdr.sys_stat_macros
    libc.test.UnitTest.ErrnoCheckingTest
    libc.test.UnitTest.ErrnoSetterMatcher
)

add_libc_test(
  openat_test
  SUITE
    libc_fcntl_unittests
  SRCS
    openat_test.cpp
  DEPENDS
    libc.hdr.fcntl_macros
    libc.src.errno.errno
    libc.src.fcntl.open
    libc.src.fcntl.openat
    libc.src.unistd.close
    libc.src.unistd.read
    libc.test.UnitTest.ErrnoCheckingTest
    libc.test.UnitTest.ErrnoSetterMatcher
)

add_libc_test(
  allocate_test
  SUITE
    libc_fcntl_unittests
  SRCS
    allocate_test.cpp
  DEPENDS
    libc.hdr.errno_macros
    libc.hdr.fcntl_macros
    libc.hdr.sys_stat_macros
    libc.include.fcntl
    libc.src.__support.libc_errno
    libc.src.fcntl.fallocate
    libc.src.fcntl.open
    libc.src.fcntl.posix_fadvise
    libc.src.fcntl.posix_fallocate
    libc.src.sys.stat.fstat
    libc.src.unistd.close
    libc.src.unistd.unlink
    libc.test.UnitTest.ErrnoCheckingTest
    libc.test.UnitTest.ErrnoSetterMatcher
)

add_libc_test(
  splice_test
  SUITE
    libc_fcntl_unittests
  SRCS
    splice_test.cpp
  DEPENDS
    libc.hdr.errno_macros
    libc.hdr.fcntl_macros
    libc.hdr.sys_stat_macros
    libc.src.fcntl.open
    libc.src.fcntl.splice
    libc.src.fcntl.sync_file_range
    libc.src.string.memcmp
    libc.src.unistd.close
    libc.src.unistd.pipe
    libc.src.unistd.read
    libc.src.unistd.unlink
    libc.src.unistd.write
    libc.test.UnitTest.ErrnoCheckingTest
    libc.test.UnitTest.ErrnoSetterMatcher
)

add_libc_test(
  file_handle_test
  SUITE
    libc_fcntl_unittests
  SRCS
    file_handle_test.cpp
  DEPENDS
    libc.hdr.errno_macros
    libc.hdr.fcntl_macros
    libc.hdr.sys_stat_macros
    libc.hdr.types.struct_file_handle
    libc.src.__support.libc_errno
    libc.src.fcntl.name_to_handle_at
    libc.src.fcntl.open
    libc.src.fcntl.open_by_handle_at
    libc.src.string.memcmp
    libc.src.unistd.close
    libc.src.unistd.read
    libc.src.unistd.unlink
    libc.src.unistd.write
    libc.test.UnitTest.ErrnoCheckingTest
    libc.test.UnitTest.ErrnoSetterMatcher
)
