add_subdirectory(resolv)

add_custom_target(libc_netdb_unittests)
add_custom_target(libc-netdb-tests)

add_libc_test(
  netdb_test
  SUITE
    libc-netdb-tests
  SRCS
    netdb_test.cpp
  DEPENDS
    libc.hdr.netdb_macros
    libc.hdr.sys_socket_macros
    libc.hdr.types.struct_addrinfo
    libc.hdr.types.struct_sockaddr_in
    libc.hdr.types.struct_sockaddr_in6
    libc.src.netdb.freeaddrinfo
    libc.src.netdb.getaddrinfo
    libc.test.UnitTest.ErrnoCheckingTest
)

add_libc_test(
  getservent_test
  SUITE
    libc_netdb_unittests
  SRCS
    getservent_test.cpp
  DEPENDS
    libc.hdr.types.struct_servent
    libc.src.netdb.endservent
    libc.src.netdb.getservbyname
    libc.src.netdb.getservbyport
    libc.src.netdb.getservent
    libc.src.netdb.setservent
)

add_libc_test(
  gethostbyaddr_test
  SUITE
    libc_netdb_unittests
  SRCS
    gethostbyaddr_test.cpp
  DEPENDS
    libc.hdr.sys_socket_macros
    libc.hdr.types.struct_hostent
    libc.src.netdb.gethostbyaddr
)

add_libc_test(
  getnetent_test
  SUITE
    libc_netdb_unittests
  SRCS
    getnetent_test.cpp
  DEPENDS
    libc.hdr.sys_socket_macros
    libc.hdr.types.struct_netent
    libc.src.netdb.endnetent
    libc.src.netdb.getnetbyaddr
    libc.src.netdb.getnetbyname
    libc.src.netdb.getnetent
    libc.src.netdb.setnetent
)

add_libc_test(
  hstrerror_test
  SUITE
    libc_netdb_unittests
  SRCS
    hstrerror_test.cpp
  DEPENDS
    libc.hdr.netdb_macros
    libc.src.netdb.hstrerror
)

add_libc_test(
  gethostent_test
  SUITE
    libc_netdb_unittests
  SRCS
    gethostent_test.cpp
  DEPENDS
    libc.hdr.sys_socket_macros
    libc.hdr.types.struct_hostent
    libc.src.netdb.endhostent
    libc.src.netdb.gethostent
    libc.src.netdb.sethostent
)

add_libc_test(
  getprotoent_test
  SUITE
    libc_netdb_unittests
  SRCS
    getprotoent_test.cpp
  DEPENDS
    libc.hdr.types.struct_protoent
    libc.src.netdb.endprotoent
    libc.src.netdb.getprotobyname
    libc.src.netdb.getprotobynumber
    libc.src.netdb.getprotoent
    libc.src.netdb.setprotoent
    libc.src.string.strcmp
)

add_libc_test(
  getnameinfo_test
  SUITE
    libc_netdb_unittests
  SRCS
    getnameinfo_test.cpp
  DEPENDS
    libc.hdr.netdb_macros
    libc.hdr.types.struct_sockaddr
    libc.hdr.types.struct_sockaddr_in
    libc.hdr.types.struct_sockaddr_in6
    libc.include.sys_socket
    libc.src.__support.CPP.string_view
    libc.src.arpa.inet.htons
    libc.src.netdb.getnameinfo
)

add_libc_test(
  gethostbyname_test
  SUITE
    libc-netdb-tests
  SRCS
    gethostbyname_test.cpp
  DEPENDS
    libc.hdr.netdb_macros
    libc.hdr.sys_socket_macros
    libc.hdr.types.struct_hostent
    libc.hdr.types.struct_servent
    libc.src.netdb.__h_errno_location
    libc.src.netdb.gethostbyname
    libc.src.netdb.gethostbyname2
    libc.src.netdb.getservbyname
    libc.src.string.strcmp
)

add_libc_test(
  gai_strerror_test
  SUITE
    libc_netdb_unittests
  SRCS
    gai_strerror_test.cpp
  DEPENDS
    libc.include.netdb
    libc.src.netdb.__h_errno_location
    libc.src.netdb.gai_strerror
    libc.src.netdb.herror
    libc.src.string.strlen
)
