//===-- Tables for iconv's East Asian sets ----------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// DO NOT EDIT MANUALLY. This file is generated by
// libc/utils/iconv_utils/gen.py from the mapping files it lists.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_LIBC_SRC_ICONV_CJK_TABLES_H
#define LLVM_LIBC_SRC_ICONV_CJK_TABLES_H

#include "hdr/stdint_proxy.h"
#include "hdr/types/size_t.h"
#include "src/__support/macros/config.h"
#include "src/iconv/code_table.h"
#include "src/iconv/sequences.h"

namespace LIBC_NAMESPACE_DECL {
namespace iconv_internal {

extern const CodeTable JIS_X0208;
extern const CodeTable JIS_X0212;
extern const CodeTable CP932_NEC_ROW_13;
extern const CodeTable CP932_IBM;
extern const CodeTable CP932_NEC_SELECTED_IBM;
constexpr size_t CP932_CHANGE_COUNT = 6;
extern const CodePair CP932_CHANGES[CP932_CHANGE_COUNT];
constexpr size_t CP932_AREA_COUNT = 6;
extern const CodeRange CP932_AREAS[CP932_AREA_COUNT];
extern const CodeTable ISO2022_JP_MS_IBM;
extern const CodeTable GB18030_TWO_BYTE;
constexpr size_t GB18030_RUN_COUNT = 221;
constexpr uint32_t GB18030_FOUR_BYTE_COUNT = 39420;
// Where a run of consecutive code points begins among the four byte
// codes, in order of position.
extern const CodeRun GB18030_RUNS[GB18030_RUN_COUNT];
extern const uint8_t GB18030_RUNS_BY_CODE_POINT[GB18030_RUN_COUNT];
constexpr size_t GBK_EXCLUDED_COUNT = 13;
extern const CodeRange GBK_EXCLUDED[GBK_EXCLUDED_COUNT];
// A bit for each GB 2312 code with a character, row by row.
extern const uint8_t GB2312_ASSIGNED[1105];
// The GB 2312 codes GB18030 reads as other characters.
constexpr size_t GB2312_CHANGE_COUNT = 2;
extern const CodePair GB2312_CHANGES[GB2312_CHANGE_COUNT];
extern const CodeTable BIG5_TWO_BYTE;
extern const CodeTable BIG5_HKSCS;
constexpr size_t BIG5_HKSCS_PLANE_2_COUNT = 1713;
// The characters of the Supplementary Ideographic Plane, in order of
// code, as their offset from U+20000, and their positions in order of
// code point.
extern const CodePair BIG5_HKSCS_PLANE_2[BIG5_HKSCS_PLANE_2_COUNT];
extern const uint16_t BIG5_HKSCS_PLANE_2_ORDER[BIG5_HKSCS_PLANE_2_COUNT];
constexpr Sequence BIG5_HKSCS_SEQUENCE_LIST[4] = {
    {0x8862, 2, {0x00CA, 0x0304, 0x0000}},
    {0x8864, 2, {0x00CA, 0x030C, 0x0000}},
    {0x88A3, 2, {0x00EA, 0x0304, 0x0000}},
    {0x88A5, 2, {0x00EA, 0x030C, 0x0000}},
};

constexpr Sequences BIG5_HKSCS_SEQUENCES = {BIG5_HKSCS_SEQUENCE_LIST, 4};
extern const CodeTable KS_X_1001;
// The JOHAB codes of a Hangul letter by itself.
constexpr size_t JOHAB_LETTER_COUNT = 51;
extern const CodePair JOHAB_LETTERS[JOHAB_LETTER_COUNT];

} // namespace iconv_internal
} // namespace LIBC_NAMESPACE_DECL

#endif // LLVM_LIBC_SRC_ICONV_CJK_TABLES_H
