//===-- Tables for iconv's East Asian sets ----------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// DO NOT EDIT MANUALLY. This file is generated by
// libc/utils/iconv_utils/gen.py from the mapping files it lists.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_LIBC_SRC_ICONV_CJK_TABLES_H
#define LLVM_LIBC_SRC_ICONV_CJK_TABLES_H

#include "hdr/stdint_proxy.h"
#include "hdr/types/size_t.h"
#include "src/__support/macros/config.h"
#include "src/iconv/code_table.h"

namespace LIBC_NAMESPACE_DECL {
namespace iconv_internal {

extern const CodeTable JIS_X0208;
extern const CodeTable JIS_X0212;
extern const CodeTable CP932_NEC_ROW_13;
extern const CodeTable CP932_IBM;
extern const CodeTable CP932_NEC_SELECTED_IBM;
constexpr size_t CP932_CHANGE_COUNT = 6;
extern const CodePair CP932_CHANGES[CP932_CHANGE_COUNT];
constexpr size_t CP932_AREA_COUNT = 6;
extern const CodeRange CP932_AREAS[CP932_AREA_COUNT];

} // namespace iconv_internal
} // namespace LIBC_NAMESPACE_DECL

#endif // LLVM_LIBC_SRC_ICONV_CJK_TABLES_H
